services:
  worker:
    depends_on:
      temporal:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_SDK_VERSION=0.5.0
    volumes:
      - ./temporalio_worker:/usr/local/bin/temporalio_worker
    command: ["temporalio_worker"]
